/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: '#6ee7b7',
          '2': '#30ab7a',
        },
        empty: 'transparent',
        hover: '#0000000C',
        hover2: '#00000019',
        gray: {
          1: 'var(--gray1)',
          2: 'var(--gray2)',
          3: 'var(--gray3)',
          4: 'var(--gray4)',
          5: 'var(--gray5)',
          6: 'var(--gray6)',
          7: 'var(--gray7)',
          8: 'var(--gray8)',
          9: 'var(--gray9)',
          10: 'var(--gray10)',
          11: 'var(--gray11)',
          12: 'var(--gray12)',
        },
        grayA: {
          1: 'var(--grayA1)',
          2: 'var(--grayA2)',
          3: 'var(--grayA3)',
          4: 'var(--grayA4)',
          5: 'var(--grayA5)',
          6: 'var(--grayA6)',
          7: 'var(--grayA7)',
          8: 'var(--grayA8)',
          9: 'var(--grayA9)',
          10: 'var(--grayA10)',
          11: 'var(--grayA11)',
          12: 'var(--grayA12)',
        },
        blue: {
          1: 'var(--blue1)',
          2: 'var(--blue2)',
          3: 'var(--blue3)',
          4: 'var(--blue4)',
          5: 'var(--blue5)',
          6: 'var(--blue6)',
          7: 'var(--blue7)',
          8: 'var(--blue8)',
          9: 'var(--blue9)',
          10: 'var(--blue10)',
          11: 'var(--blue11)',
          12: 'var(--blue12)',
        },
      },
      backgroundColor: {
        'app-bg': 'var(--app-bg)',
      },
      textColor: {
        'text': 'var(--text)',
      },
    },
  },
  plugins: [],
  darkMode: ['class'],
};
